{% set data = load_setup_py_data() %}

package:
  name: biovis-jsbase-plugins
  version: {{ data.version }}


source:
  - path: ../


build:
  include_recipe: True


requirements:
  build:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - biovis-report ~=0.5

test:
  imports:
    - datatable.datatable
    - pie_chart.pie_chart
    - pivot_table.pivot_table
    - tabulator.tabulator

about:
  home: {{ data.url }}
  license: MIT
  license_file: LICENSE.md
  license_family: MIT

  summary: {{ data.description }}
  description: {{ data.description }}
  doc_url: https://github.com/biovis-report/biovis-jsbase-plugins/blob/master/README.md
  dev_url: {{ data.url }}