{% set data = load_setup_py_data() %}

package:
  name: biovis-rbase-plugins
  version: {{ data.version }}


source:
  - path: ../


build:
  include_recipe: True


requirements:
  build:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - biovis-report ~=0.5
    - r-dplyr
    - r-shiny
    - r-plotly
    - r-ggpubr
    - r-rcolorbrewer
    - r-shinybs 
    - r-shinyjs
    - r-shinydashboard
    - r-ggvis
    - r-ggplot2
    - r-colourpicker
    - r-d3heatmap
    - r-shinycssloaders
    - r-ggcorrplot ~=0.1
    - r-upsetr ~=1.3
    - r-scatterd3 ~=0.8
    # Biovis Channel
    - r-mutsneedle ~=0.1
    - r-configr ~=0.3
    - r-biovis-reportr ~=0.1

test:
  imports:
    - barplot.barplot
    - boxplot.boxplot
    - corrplot.corrplot
    - density_plot.density_plot
    - grouped_boxplot.grouped_boxplot
    - heatmap.heatmap
    - heatmap_d3.heatmap
    - lineplot.lineplot
    - lollipop_plot.lollipop_plot
    - rocket_plot.rocket_plot
    - scatter_plot.scatter_plot
    - stack_barplot.stack_barplot
    - upset.upset
    - violin_plot.violin_plot

about:
  home: {{ data.url }}
  license: MIT
  license_file: LICENSE.md
  license_family: MIT

  summary: {{ data.description }}
  description: {{ data.description }}
  doc_url: https://github.com/biovis-report/biovis-rbase-plugins/blob/master/README.md
  dev_url: {{ data.url }}